### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by qiaodenghui** [MyScript/interactive-ink-examples-android#13]
Process: com.myscript.iink.demo, PID: 14799
java.lang.NullPointerException: Attempt to get length of null array
        at com.myscript.iink.uireferenceimplementation.SmartGuideView.computeModificationOfWords(SmartGuideView.java:626)
        at com.myscript.iink.uireferenceimplementation.SmartGuideView.update(SmartGuideView.java:531)
        at com.myscript.iink.uireferenceimplementation.SmartGuideView.contentChanged(SmartGuideView.java:378)
        at com.myscript.iink.Editor$3.accept(Editor.java:156)
        at com.myscript.iink.Editor$3.accept(Editor.java:152)
        at com.myscript.iink.ListenerList.forEach(ListenerList.java:53)
        at com.myscript.iink.Editor.contentChanged(Editor.java:151)

**Comment by myscript-developer** [comment]
Dear Qiaodneghui,

thank you for contacting us.
It seems you also submitted the above question on ou forum?
If so, can you confirm we can close this topic?

Thank you,
Best regards,

Olivier
