### ISSUE TITLE
invalid certificate

### ISSUE THREAD

**Issue by lurongshuang** [MyScript/interactive-ink-examples-android#14]
Hello, I plan to use myscript as a plug-in for my flutter project, but when initializing the plug-in I encapsulated, an error occurred: Engine.create(MyCertificate.getBytes());
What makes me even more confused is that at this time, I used this certificate in a newly created Android native demo and it was initialized normally! !
I'm very confused. Is it related to the project structure? Or are there other configuration issues?
hope to get your reply 

  Process: com.example.myscriptwidget_example, PID: 22914
   java.lang.IllegalArgumentException: invalid certificate
 at com.myscript.iink.NativeFunctions.createEngine(Native Method)
 at com.myscript.iink.Engine.(Engine.java:20)
  at com.myscript.iink.Engine.create(Engine.java:40)
 at com.example.myscriptwidget.engine.MyScriptEngine.initEngine(MyScriptEngine.java:71)
at com.example.myscriptwidget.view.MyScriptViewFactory$1.run(MyScriptViewFactory.java:39)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:238)
 at android.app.ActivityThread.main(ActivityThread.java:7820)
 at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by lurongshuang** [comment]
@myscript-developer   Thank you, waiting for your reply
