### ISSUE TITLE
Application error when no string entered

### ISSUE THREAD

**Issue by bubal93** [MyScript/interactive-ink-examples-android#2]
If you write or draw nothing inside the Editor view and hit "Convert" button, application will close with this error:
`18886-18886/com.myscript.iink.getstarted E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myscript.iink.getstarted, PID: 18886
    java.lang.RuntimeException: internal error
        at com.myscript.iink.NativeFunctions.convert(Native Method)
        at com.myscript.iink.Editor.convert(Editor.java:839)
        at com.myscript.iink.getstarted.MainActivity.onOptionsItemSelected(MainActivity.java:173)
        at android.app.Activity.onMenuItemSelected(Activity.java:3380)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:368)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6360)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

And if you will enter something, then erase it and hit Convert - the error won't occur.

**Comment by q707172686** [comment]
**an error occurred when building**
Gradle sync failed: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 407"
			Consult IDE log for more details (Help | Show Log) (1s 849ms)

**Comment by MyScriptSupport** [comment]
Dear Bubal,
can you please try to upgrade to the latest version of iink?
Best regards,
Olivier
